#!/usr/bin/python3

#SHERLOCK © 2020 - Claudio Nanni

# Module Imports
import mariadb
import sys
import os
import time
import json
import requests
from datetime import datetime




def dump_commands_from_db():
   # For database management of commands, periodically they can be exported from the database (if mantained there) and dumped to json file that should be then uploaded to github
   listCommands={}

   try:
      conn = mariadb.connect(
      user=par1,
      password=par2,
      host=par3,
      database="sherlock",
      port=par4)
   except mariadb.Error as e:
      print(f"Error connecting to MariaDB Platform: {e}")
      sys.exit(1)
   cur = conn.cursor();
   print("Loading commands...")
   cur.execute("SELECT ID,TYPE,USER_TYPE,COMMAND,DESCRIPTION FROM sherlock_cmd ORDER BY type desc,cast(substring(ID,2) as unsigned)" )
   for (ID,TYPE,USER_TYPE,COMMAND,DESCRIPTION) in cur:
      listCommands[ID]=[TYPE,USER_TYPE,COMMAND,DESCRIPTION]
   print("Writing commands to json file...")
   with open('./sherlock_cmd.json', 'w') as fp:
      json.dump(listCommands, fp,indent=4)

par1=str(sys.argv[1])
par2=str(sys.argv[2])
par3=str(sys.argv[3])
par4=int(sys.argv[4])

dump_commands_from_db()
